name: fthmobile
description: FTH
version: 1.0.0+7
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.8.1
  provider: ^4.0.3
  http:
  font_awesome_flutter:
  shared_preferences:
  email_validator:
  timeline_tile:
  google_fonts:
  url_launcher:
  flutter_html:
  image_slider: ^1.0.2
  cached_network_image: ^2.0.0
  flutter_native_splash: ^2.0.4
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/slider/
    - images/status/